name: Bug Report
description: Report a bug you found
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea #description
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea #reproduce
    attributes:
      label: How can we reproduce this bug?
      description: Are there any specific steps you had to take in order to trigger the bug, and what is the expected behaviour we should expect?
      placeholder: Kindly elaborate.
    validations:
      required: true
